apiVersion: v2
appVersion: 1.27.2
dependencies:
- name: gitea
  repository: https://dl.gitea.com/charts
  version: 12.7.0
description: Gitea Helm chart for Kubernetes
icon: https://gitea.com/assets/img/logo.svg
name: gitea-umbrella
sources:
- https://gitea.com/gitea/helm-gitea
- https://github.com/go-gitea/gitea
- https://docker.gitea.com/gitea
type: application
version: 3.0.0
