gitea:
  image:
    tag: "1.27.2"
  service:
    http:
      port: 3001
  ingress:
    enabled: false
  persistence:
    enabled: true
    mount: true
    create: false
    claimName: gitea-pvc
  postgresql:
    enabled: true
    image:
      tag: 15.10.0
  postgresql-ha:
    enabled: false
  valkey-cluster:
    enabled: false
  valkey:
    enabled: false
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      actions:
        ENABLED: false
      database:
        DB_TYPE: postgres
      server:
        ROOT_URL: http://gitea.nuc.one/
        DOMAIN: gitea.nuc.one
        PROTOCOL: http
        SSH_DOMAIN: gitea.nuc.one
      session:
        PROVIDER: db
      cache:
        ADAPTER: memory
      queue:
        TYPE: level
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
