gitea:
  service:
    http:
      port: 3001
  ingress:
    enabled: false
  persistence:
    enabled: true
    existingClaim: gitea-pvc
  memcached:
    enabled: false
  postgresql:
    enabled: true
    persistence:
      existingClaim: gitea-db-pvc
  postgresql-ha:
    enabled: false
  mysql:
    enabled: false
  mariadb:
    enabled: false
  redis-cluster:
    enabled: false
  gitea:
    config:
      database:
        DB_TYPE: postgres
      server:
        ROOT_URL: http://gitea.nuc.one/
        DOMAIN: gitea.nuc.one
        PROTOCOL: http
        SSH_DOMAIN: gitea.nuc.one
