gitea:
  service:
    http:
      port: 3001
  ingress:
    enabled: false
  persistence:
    existingClaim: gitea-pvc
  memcached:
    enabled: false
  postgresql:
    enabled: true
    persistence:
      existingClaim: gitea-db-pvc
  mysql:
    enabled: false
  mariadb:
    enabled: false
  gitea:
    config:
      server:
        ROOT_URL: https://gitea.nuc.local/
        DOMAIN: gitea.nuc.local
        PROTOCOL: https
        SSH_DOMAIN: gitea.nuc.local