gitea:
  service:
    http:
      port: 3001
  ingress:
    enabled: false
  persistence:
    enabled: true
    mount: true
    create: false
    claimName: gitea-pvc
  postgresql:
    enabled: true
    persistence:
      mount: true
      create: false
      claimName: gitea-db-pvc
  postgresql-ha:
    enabled: false
  redis-cluster:
    enabled: false
  gitea:
    config:
      database:
        DB_TYPE: postgres
      server:
        ROOT_URL: http://gitea.nuc.one/
        DOMAIN: gitea.nuc.one
        PROTOCOL: http
        SSH_DOMAIN: gitea.nuc.one
      session:
        PROVIDER: db
      cache:
        ADAPTER: memory
      queue:
        TYPE: level
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
