apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  serviceName: "wireguard"
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard:1.0.20210914
        envFrom:
        - configMapRef:
            name: wireguard-configmap
        envFrom:
        - secretRef:
            name: wireguard-secret
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN
          privileged: false
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: wg-config
            mountPath: /config
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: pvc-wireguard
