apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Berlin"
  SERVERPORT: "{{ .Values.wireguard.port }}"
  SERVERURL: "1.2.3.4"
  PEERS: "3"
  PEERDNS: "8.8.8.8"
