---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-secret
  namespace: wireguard
spec:
  encryptedData:
    SERVERPORT: AgCU0g+iX+ST0T+d/XG9NEFNheVhKGHLyXSRIhTVIc5rmTemivuKmIPkNtPQrkGXqaoQSESFB019Ed1NeRcdgg5yfk/gEBeuWW1+Jn7HM7+kYQY3H77CUIwykIM7Tl+kKtNzB+FH3eIJ3smnw+LBwTGPDIWE0dzMu7R4x8BTK4IalUJ0jRlgujLEQ/GWAf8jOI9EwYNtLUqeCnx14guYiaoa8mxFTWBZ+NtO/ofI1mdJa+laCKa8lIjXViS+z6T0IVk7S4zN9PfTBtesLXx2J4mqPcrMVbPD6pC1SVDK+J1X7nV7fI+dT86TABjOcimu0X2djbc1Iy/YDYNrtAGo7YdVvT+W+vYsKUBYOYwHfeOC5WU5OZXPoSJQphfpamxnyhSCle7nVbq3OzkS4xlhQxGgm7AnEUHlUdixfLeth+TcfuRuQLgCGfl1eWm8Ryk1TyQy189PUztiompDk6anGqCVMwleoKsn5XIo+z7VXMu6/QsqWzN9a4K3GbcX0ih0IK1EwTix28lCnvEsudRDWsl8U8T4P1fa70A7j1hx/SBTx/QOCSg0P/tjtY+AqmVERndwsNHvK0IHajyy0jV9CO0IC3QJHsVPbA8KJBrk7q5F1F5rLxQU/CgUYH8lL+U5XvZYluIt196u026Dbux1zxqMI8zwY7iKD0AlZWnDTjiOW5ku5NzP+rZN51nvEVKDohu6Tru5hQ==
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-secret
      namespace: wireguard
    type: Opaque
