apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-screenshot-pv
  labels:
    type: local
spec:
  storageClassName: hass-screenshot-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/hass-screenshot"
