---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-auth-secret
  namespace: mongodb
spec:
  encryptedData:
    mongodb-passwords: AgBwJ/ki2oZ3idwUGg6M9Eec/g8f/5awkNFtxIHu4Y8/1a0v6lVkM1Im9LoU27P8Lt/9Lj8wH4sNEzLX/TZulnlcttXf751iBJ+t2dNLiibSC1GQw4zzBf7GMYLAmc63fvvpVEg0Bakreel+KCs4fk/mVV5zmhDBiMJKrdNUfkufhdtdFdynQmnXR8xo5yaevc0jtDRyun/uSpQQviCgUQg4irvtMNgqGz3pcM+qc0YV7JyEogNqw9/GenZqAYJvbHJvB4/O4F5J1+qFu/CoBmHQbjUaGaDP0wQaGXGAf49lsF2CtyLMN1yW1mjL2koTE5qSsDTLWX1DbY/khCR1X1OE+lce/+PrBH8i8e53SzI4Roa06o7bKNjYg73Etvo9AI+CZ0oKUjrbfuYGyriq3ZJ8AxlEtQ9M7EVb9Yvv/PC5ycvS9Jhw6T5N78TfX0n2921oYEzYDOfB9ifzihKqn3RyB3G/+w0QM1OeWWELND3NKrqPG+Ch3hdvAPUuouNTo023H6a5HiTOUBAfNHdEVnKASze4bcZ13dHzJlJ+Tn/UgBdPn+dY/0nZAx+NF/Vou7YaHriZ6LahYBtQaeIbe1TGkBNXzreQLUqPEy1c+blsjkvzx1jPLoxHB3HM58HcMwnREhMq0ZYPXm/8ZF14Uw1yTVVeoRN+ylLIAwFKJvafJFfmh892v2s5eKt9Umq+hgse62UB1l4ysEhFYW97SXuR
    mongodb-root-password: AgBT5pxvPvfJhsxeMG3+MiD2MqzlaUrtyC5maCzTd28ee1XARfvC6Ed/eKs8LS/vxs3/Z4Evc/jNIBFw0JdQQ73jnhuGG9SyNPCDBWLhVxT8+59mrgfgjnfXsv3ZedbGR2sZx4WXswv21kM8FNj3yIzylrOSpuwc4aU71jnCSrqQfF+EP3IMF9G+YceWbAOXDagOOfSR7Vg/J6zgE6nrOHj+9FPKSPcDhdvuBzAYA+2YmuGPMH9k0XdCkCQvDWuklkBOtdktJuE659VPlty/sAnPZfbfGbpkgBfdEjw3QufO0Q3nAzvm220zdMAjTapArlYYGF9MA1ay7J5tn5NMZiCiHXOKxEwzlFloINaPcZT34obZ+1dP7eSJhl75RJKL7iUz7XnwyTcO/vpJveJCMqNpfp3X4E2fOnbG/yHvTqT1j46yZ7OcWxKkmWuxLtEOHaI+R49VvBj7dXTgG9838hx88IROYg4/9h4P7ask9b+sa5clg50fTB39z/TlRY2dmyEM0mc2d+9IPkL0TWxUETyuSNUX+ZpwnMjPbqbzV5Rf2Czu6n28Li02MxqPoHlz8UPa2ycwc7QAXRxj7Ha2fofuYnUlilIoP9TtNPTOYPblsXDsBPAtkPZivRbj27ihXjUHRuIt4BHAwCqk97npZlstHwrz1uBWHmuXwAFaQ54A5z9WtCPN9Oeln3rbhMVCASv6dXzcPSIWOel4Atsv3Qew
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-auth-secret
      namespace: mongodb
    type: Opaque
