apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itobey/k3s-nuc.git 
    targetRevision: HEAD
    path: deploy/datadog
    helm:
      valueFiles:
      - values.yaml
      - values-custom.yaml
      - secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true 
