apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hass-screenshot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itobey/k3s-nuc.git 
    targetRevision: HEAD
    path: deploy/hass-screenshot
  destination:
    server: https://kubernetes.default.svc
    namespace: hass-screenshot
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true 
