apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itobey/k3s-nuc.git
    targetRevision: HEAD
    path: deploy/music-assistant
  destination:
    server: https://kubernetes.default.svc
    namespace: music-assistant
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
