apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf-fritzbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itobey/k3s-nuc.git 
    targetRevision: HEAD
    path: deploy/telegraf-fritzbox
    helm:
      valueFiles:
      - secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: telegraf-fritzbox
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true 
