n8n:
  fullnameOverride: "n8n"

  timezone: "Europe/Berlin"

  redis:
    enabled: false

  ingress:
    enabled: false

  main:
    persistence:
      enabled: true
      existingClaim: "n8n-pvc"
    
    extraVolumes:
      - name: n8n-input
        persistentVolumeClaim:
          claimName: n8n-input-pvc
    
    extraVolumeMounts:
      - name: n8n-input
        mountPath: /data/n8n-input
