n8n:
  fullnameOverride: "n8n"

  timezone: "Europe/Berlin"

  redis:
    enabled: false

  ingress:
    enabled: false

  main:
    persistence:
      enabled: true
      existingClaim: "n8n-pvc"
    
    volumes:
      - name: n8n-input
        persistentVolumeClaim:
          claimName: n8n-input-pvc
    
    volumeMounts:
      - name: n8n-input
        mountPath: /data/n8n-input
    
    extraEnvVars:
      N8N_RESTRICT_FILE_ACCESS_TO: /data/n8n-input
      NODES_EXCLUDE: []
