apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-pvc
  namespace: music-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: music-assistant-pv
  resources:
    requests:
      storage: 5Gi
