apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  labels:
    type: local
spec:
  storageClassName: home-assistant-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/home-assistant"
