kind: PersistentVolume
apiVersion: v1
metadata:
  name: wireguard-pv
  namespace: wireguard
spec:
  storageClassName: wireguard-manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/docker-volumes/wireguard"
