apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Berlin"
  SERVERPORT: "51820"
  SERVERURL: "95.217.154.222"
  PEERS: "3"
  PEERDNS: "8.8.8.8"
