fddb:
    user: ENC[AES256_GCM,data:sAT04KBS44owQzO9wI98hQ01qUQW42NeNXeCWA==,iv:0ojOWi+hQ8YikxUh0nlkXMgDFdxDrEhOJiETAipvEQU=,tag:itHRGGI//0Ohz8pEKnyOZw==,type:str]
    pw: ENC[AES256_GCM,data:6ZyXoWy8rSt1JvCWuCpS1g==,iv:cxly6e8QeGw1jBZn/GthETXNxXmeZDnPzyD78EHRhuc=,tag:8M92GdzlG9tYMQoIQNCmLQ==,type:str]
    cookie: ENC[AES256_GCM,data:q4C43/HS59PfxxbOZad2tFQ5LRx5BPVL,iv:nMDCAVocObvVZdkMYmSHOY36UvLsv9U8LDUl9k1wgco=,tag:KUDouWZlIqiU8+m/r4l7JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17f7w8ddvxm4mrgpl0h7r8ng48lc9qmgj0fgsa4jnd399mtd2j5qquf59m4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYVBDTzVqRWEwaGlhbGRk
            K21IM1ZlazdpbzBOUFh1Rm85dnpZbC9mcFJFCmVod0huZVZRc0lFVkJ1bFhQOTNk
            NURVbnlGYU5zWlgwV3B4QmZCbDQ2Z3cKLS0tIHo1TS9UNlc0b3c1NFkrbGhOMmgr
            RURjd1l1MzJFT2dwalkrbFdCQ0VhVHcKUayeYMxcnGrv5LBwlU9IAa/BeM4mWJES
            oQ+fzgy0K7VnBHgbbyA80pJeZ7PuFyIf6h3dcw7k5sbbbT3nL3lJqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-06-06T11:10:07Z"
    mac: ENC[AES256_GCM,data:3fT5G0IXD25Z33RnP90xj4cjsqoKuWJL7LuzKHhD+nlqoUWlpv+LR4fTq2xy8CRrg68C3xbLD0Bg9xsa56jda2N+I3A9jl7s5ZJ5Zm2ksjVPQ4E/c/8dEQD4fcMR/l7dveB4dHLJ1AWRFoFUYEuRC9B9qXYXTW1/5kL3dQGUl54=,iv:ZzKfoKEB8zS5CB7QOanAhaLYuMDi+gR+4PkdvWsg5tU=,tag:5Udin9zQcC2Fl8d+54UPww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1