cloudflare:
    token: ENC[AES256_GCM,data:mf2r30ePjAgE4Fq3rB0hghGbxKbq8kbA/JDA00CeNgL3OCwaYmhzYA==,iv:d7/QoX7WQ8Vbo1WpY9onfuYPbOfOSJm1CI4Kpt2vgpU=,tag:Iu1SdNIMUXqO2ZevY/4nng==,type:str]
middleware:
    basicAuth:
        user1: ENC[AES256_GCM,data:z/23hBJPIjqgxhdXrv+2Z4a2Nrhuc69BBiu6Uu+ZDEwutV5xnzYp0q+Vh8X0uiwNAg4MsywuoJlJkwgP,iv:8Vjfcj/9b9FzDGojNyHmNj96EARhvaxvCqsqA3/1Y+s=,tag:E+tMmUiojvYByUC3aYLRXA==,type:str]
        user2: ENC[AES256_GCM,data:fW6TPr/BEILFgI2zDygq3uynWeAusC8xOw1PPWxTkdaOZkCXSzQpCce5JcUwCVLPlBHLf707wSUlBp30,iv:uExF3Uh03uvcoMxhpNm9JgrW8dyHjvihNgZyOYlOKck=,tag:j/8BuBC5cP0lkZiR7iekzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17f7w8ddvxm4mrgpl0h7r8ng48lc9qmgj0fgsa4jnd399mtd2j5qquf59m4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaWJZQjE1dTBOVmZiMjRO
            K1R2LzFyVnI3bmJQNVJhYW9NMlZhc0p3QUVvClc1WVVqVmQzMVV2c25oZXRvUENj
            WWlKT0ppNHFobE1oeDlPdWprZlVpdk0KLS0tIFhybDEwNndTeEdzOU51MldEZUo4
            aHFpNGQ2RkgvN0MwdjJkc2dKVXF5TVEKXbkKDkH2ZKmpVTFQCmqTzsHsvmZbQd9s
            2C7DQqXbn1dpa9Dz3tlogkyHay/ljeP5HZSDDi3Bn4HRKeJeBUhZvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-05-22T17:11:05Z"
    mac: ENC[AES256_GCM,data:mez21go9A91DzGuJMT7uFZRhwrQwnOkI8kogXBYLb2ToJc4gKT793HfqLQMEqCHxVIL4WV2a5FKeA4Uo4WfrTWglgVneWf5E/h7DEqZcbF04RkxS0K3IzVXnEVk62tD7N8+xYkDcStC5XLHGK9wkcmb5Q8BsUFLhW5ijL/NCVzs=,iv:sHE9VDh+7CYiHvde899pNy11cOCfSymOu1+2+2Z9Ssg=,tag:KFAUcvvTA14U76v5lEQtSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
