apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-input-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: n8n-input-pv
  resources:
    requests:
      storage: 50Gi
