apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-input-pv
  labels:
    type: local
spec:
  storageClassName: n8n-input-pv
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/resilio-data/folders/tobi_handy_sync_folder/_aiserver"
