---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAaesDI5z0Gf7YdUrTw5adfqzM5tg5x5agEXTQb3m9aqFWPhmFrwhy0IbgqOp5p7EZPnxbJ4DoArxfoNX6cPnKoGCSuU++x1OqI5/sHK85OcgLe9mQ+qmKE72l5BPv3BEwLDzBGrNE33FiPw4mmpOBjEFbZjXleBhab1Io9VkS9QqrICdKpUUMDMot5XJaQr3KLmsOgR9Uixxd0UsFUG56FK/IRPROyKvmmeWC5j0/Z1eMD4HFThcF+H22xe5nZ96S4Df2PNCYPI/Wu6/fhialUkwC1WNztoR1omy2SmpJwoRMTkql0CPqHxWgn+vblgJPpsyS8+ZsHFL5SpBRnStX3cZDzwfkGSNVx4TYYbSX7zGB8f2sFUnZd/08dz3R20GjJApQRkX9oekk/vtrX8jF0gQzdbQ3Sh+wp31nBZwqqsp4C6kZ2kHj8MQsI7OlO+qGv+y+7aOzT2dfmEHt4m7ZRx5hWxgOnfMfU9F+LzRXdQxpQT1FCChVXgaQ4M9gpWbqY3I2eEIEo/2oyz71d+wGciUk/bpeBIawGGy+J0hMaYPIYG2JOcTzYQsqK+xlt4IuoFT+DlnBWA5NCggtbP2m0T8B6MeR5Q/LdOyAvk8BU6SDuX1XWEgAeVcfkelu5wDGM/1DI77SYbt9xuTKVfd3zTJNhFW07rgGFsD7GddtJqjA/HibdF1IHw716JgItZrQ5C4T0AhwGBnAnYtLzOvGyAA330i6ijHg2A/JE6crlDw==
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
