apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-pv
  labels:
    type: local
spec:
  storageClassName: zigbee2mqtt-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/zigbee2mqtt"
