apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-pvc
  namespace: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zigbee2mqtt-pv
  resources:
    requests:
      storage: 1Gi
