apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc
  namespace: homer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homer-pv
  resources:
    requests:
      storage: 1Gi
