apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stuff-control
  name: stuff-control
  namespace: stuff-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuff-control
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stuff-control
    spec:
      containers:
      - image: itobey/stuff-control-service:0.0.1
        imagePullPolicy: Always
        name: stuff-control
        env:
        - name: SPRING_CONFIG_ADDITIONAL-LOCATION
          value: /stuff-control/
        volumeMounts:
        - name: config-volume
          mountPath: /stuff-control/application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: stuff-control-config
      restartPolicy: Always
