---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stuff-control-secret
  namespace: stuff-control
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBlA4FQtuBwgpqEq0x9xsrWgE6TzoUw+j7ANs4wu4dt4JxUVYFTWzVHOwLKahb1Z2mO2g+eu/rfl+knBygHlqq4vG/9ykD/z3mQlaPCUpaFqWDNUzu+nCvvgiwS5o5poYUjFzDDXCLtVeuicsVbzc9p2ycVe5wqeR0LRLTctFZwSGOX7mbHoWCo3uAF/j6LIcHG4j3VgoiWTvAjvDlZYGBmzarg6BAilGTOOeDnq65QQy3jIzXThiXaQzh/cx964CqbGI5L/0NRQ+XJ46c3CKcH7EifBP7jAwr54yW1bEljwSPi1LAamPMkq6z6rIBga2wrskviuFLX3eiAwzPdMOv34V/1EI9L9DnXSKQdEPGWCeCdBtSySoL/GfGeweTXB1KH8tsdDuNvvcvhg0mnY13WTGbaRrl8F9itmu80KjMidEuSn8EE1AQhTYYKoJDnocu6/qpmxgDj1TKbcxYlUlK4X01Xjt/QBqFxuGIxMUSPNtJnxDucRCqZp+3vudRZH1Fug14GHQQjYlkHbp39kLGutEkk2cNbpaRASzTHSrcQP5r05oNWFQLkt11U8iKcJfu76gEJhBEnGtDwVYSHnQddkMmy/YG4dkUswbTiYe2j8uTKQ8jrganRyT+7YaHWx8rYnEeqgqnt8GJopmxl/D0VBkX768R2ncKSsdWpA3TZ9XQBqppba6Q3hFG18UnW8z3u3AISGp5N
  template:
    metadata:
      creationTimestamp: null
      name: stuff-control-secret
      namespace: stuff-control
    type: Opaque
