apiVersion: v1
kind: PersistentVolume
metadata:
  name: baikal-config-pv
  labels:
    type: local
spec:
  storageClassName: baikal-config-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/baikal/config"
