apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  ports:
    - port: 9001
      name: mosquitto9001
    - port: 1883
      name: mosquitto1883
  selector:
    app: mosquitto
  type: LoadBalancer
