---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-pws
  namespace: mosquitto
spec:
  encryptedData:
    mosquitto-pws: AgAs4945jTuIJ2GXumlw+mCZmxhk0lSjjGfGqkbeaTZ+tMUXvjWEIQ3u0EfNBfS6Gr3kv/lpZnipYtScY/JJWIJsfznC5s6zlyr0nVcVzMflKbyZbDHp27w2O+NJqVKsu7oifWqQvvc05Jl1fFDpumFPsKtHA7ycEt6/Qc+kTbdKEDFyatA4Ve8iMpZFxQSN1y85VZZuWV86XEBTXvNHMQPJjvhc8IE/2Lm5fioWuoGccLzB7vNoVuxMDEaeD8/pDqL+GP/rhPdqxEcUFH+piPrNQeQepPXf9S4Yqk0moa2RY9phebkgjGGQEpvvBw1a9Yuhm2icCybXq46ptrjlXpSQDrvy1oln0/tt/kyGfPajwyVzNfrVNqFAdC5IwwO9JFET4KeGXiY9MeIRhjvOZD0f+VINOuzt+hknYNp/Akgb9oeYoCHN1B2N137zZHoSJ56wbRp0+fV5ZZmh2kEVVA1hX8J36Aw667KRKr3wCD0DEXDlJuBq4PVXWoEVN7DBaRDtU+ME+Fvy5yokRMoRZGV6GNju5a7X0Qm3wa2DceorQ0ToTjCVkPQdsiQchuN1NnkQQiKxEA60SniaLD4cAxS/twKGWAPFG9Byw4VGxIW5T2Gr8bVoKsriR5Memuslhdt4MAP23ANIKbWQMNnZYNY0bbSxig/uNQ87XKZMLsk0cm3rtxLx5PdCjXbSllTEO7TDyg/fIc0LL5LX+ffa6Nh+pQzqMOGeYWa6nIZrXJ92kwxusaeA1PHaSmmlBCPqS5+E5wu3ZyZQFVwdY4Qki6b4ltT8BTfhX8Zyf2T2FVTkBPcwOizhQujNB9rm2jFqw056cB27udFq9oPWGzpwM/A+n9LSJ2g=
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-pws
      namespace: mosquitto
    type: Opaque