apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: mosquitto
data:
  telegraf.conf: |
    [[inputs.mqtt_consumer]]
      servers = ["tcp://mosquitto.mosquitto:1883"]
      topics = [
    	"home/#"
      ]
    username = "$MQTT_USERNAME"  # Reference environment variable
    password = "$MQTT_PASSWORD"  # Reference environment variable
    
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb2.influxdb2:8086"]
      token = "$INFLUXDB2_TOKEN"
      organization = "primary" 
      bucket = "home"