---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb2-token
  namespace: mosquitto
spec:
  encryptedData:
    token: AgAxf+FB5h9iMAptScDgb/v1Wvk80551auDYEDf4aTsgbWYwwbAxad9bxTiurFN2lWtJWv7kNpgOkAecgbux5tshsx8o/IwuzD+EdBazLEeBQ+xzYpEY52lT00IhXJYbCEJ8xDwZdpaIaTdkKlqgemFag0+DcDhdC98oIzkfxcfUIoMgxCG5iucq9BEKQz+RpwAizLikcCQI+wnU66yqABRFyMtoimYo3POWXe9cAO4QhQsnhOsLn1FtsRUBedVDXDKfFM09XtnP9wvqXbRAocLHdf0+6z96CSz/AnQXRyk53AqIVEvote2c83umuD928PIJ73o+KzW4HNZi4HrxEByltIT3kZZeaE3p+/mv4ddbNSNKD/MWCEnlSp3BIfaw0096sOw2W0MpZjEKEG+TPPintjH2c+EG7Y438zrV4tLm4PyeP7mdv3r0lSS/JhOZB7VKzm4XLZ0LTCK4CWGtPXN0S0K/2zhGlYCgG7WPrpuSZjWvHqKfh12RMbW65QbTCA086k5ugh1Yv1QKjDO2bAlacyOZy8+vzCRJJhyoovfSVzqZJ6P9QIM99TKQ1YHzyaUPBkKsPm+qiLXk4wECTS5XpobldzNa7Mmx/+yMeG2fSqFgh3OtYxQs15VQKqS9lkA8SPwWyIluOKwkU26xpDwP0PiT1ICA2S0mgLZe8IxWkxRQXYIUXiMBUVaBPZEevweobxGezkHLORo2Qec2pb91LdGg11UFh3X0fVfozAquo/Lunxs5l4GQENm972RYU0XNP3EjrkhNsZH6+d+XTbeEYxQe6htnwExLTxqVG36whcfMl1XsE4SH
  template:
    metadata:
      creationTimestamp: null
      name: influxdb2-token
      namespace: mosquitto
