apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
  namespace: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf:1.28.1
        imagePullPolicy: IfNotPresent
        name: telegraf
        env:
        - name: INFLUXDB_URL
          value: http://influxdb.influxdb:8086
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: telegraf-mosquitto-secret
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: telegraf-mosquitto-secret
              key: password
        - name: INFLUXDB2_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb2-token
              key: token
        volumeMounts:
        - name: config-volume
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
      volumes:
      - name: config-volume
        configMap:
          name: telegraf-config
      restartPolicy: Always
