---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAtHTX7V7FPpIbjFPxKW/HhVO/octKEQykElifzGQtPFLKMyoyMLjvlsOmKg1Q1/US31aBALkhiR5rRtP3qt3oVgaM+Pe3HdRyo7kAz8VkRO2UB/WlgSE/8U8VmKWcxWr6Km/PtCBuwOJbcmZPNQuoA7ArcXPwj8a04Z6sQ8smloa/qCs8wJEuQDpVeignTBUGSWHclanfmxyApGg/w35vLAn1ggBYaATOJssnDP1Uguahqes5Y01X8y1E+IS3bIdYrFoYv6yZIEAgnQGNzx+9BJTF7WnZGItPZqJIAA/RBgBG/T1yE+nW1ArcTG61mzDXImOPtTSZdMFbup/KhX9f/iVtxtijUfqvKC8NZCMWTAW1rDbc+8Zs8Zx4GvED27KImZluwxx++YMrqh2QfSe8/fo2+d3CWlmpQK788whhaPJLcaiLceMaESJW/FJZdLC8RBKLwL4y/xkLcqcEhzS/2wl3ckL0rcDXW6L+UsXDDepkThxWu6uQ4Mg4gIbNvgP3m+3lF/uL88Zyp4+TYO4dYmCCdqlaTEdRDugIddfCzysBl77bIjkv3y2Z82tgo5m5IwCPeq5W5ZByMYPWNU4ouygxpkbVJ6inWPnNJdX5nHhLu9HlkpHoC9UrWqY2FryZT5QcivyaN3kIZrC9rtv8v86ky9i3wVZ5ysOt2sKUr+pxrKV8s9RoO9SVKFY/75nOFoqgVAGbItP2Vw4helFmkGUMoY9c5tGVZ6LzZoH0ltOSbSFGChsuq
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque