apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: kube-system
spec:
  secretName: wildcard-secret
  dnsNames:
  - "*.it-obey.com"
  - it-obey.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
