---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBrWYJb9MgmLcH7816ZiLVvhL+tB5zrrk3JxtLFT5LUcaV5z4EWX2jJJ36XHgeCEWl1oZOCzhUy5GWokNN1T+BQBFe+Ngfw9FWcEgCZKbQb4Ljo+VdraO+zGkGgge/GYNjlGD0CrkPDbC13iCUEHfQBWpeBQ/SJhQmc78w5kpFxTaZa6hUK8jupUc/8OXZSmIjSuTDofEdU6EANyuARV0UkrWGHNS/7g8wUVq/pXGKs0rkYmXUoZ6XMDhp8LyW9iMmCvvG3DEv72CvgOXXzJ9O+HhPusmkwNmXPFEi4fnP6I55PCErZKnFW3XzlAwCEzf2qjFZAAklBWfY1pFlCTV0xmjWh69OmL9A1zsWRVQL/Kfpci4m8lNarHQsmUjsW2yJyOoxgUOelfLFdKh+RmH9XglwKx1c3Jqx345i8RtI/g/iFS/eluVrWRKzZ6Z21kQYnQpdIOTQfl2DTmsdQV367HR4vuV670/hmPSUf7vkvPzrnOWR30CGCy/Pg2xyDIbCdz5emn/aL+UpiPC+Wo13NFZzhNz4Mu184mgCzZN4zxYXXvIdg1lm1I5bnaCkLRQY0VYcnF989l0+rw+og6uHUnsE5FAg1EcIjm/O+XXNsQE9kcQfl4voRF2vOFLK1kj3JmMYqK9EmAhX9XI1Q09DbZAJj1ZY17wsuGWYfqSv67AVRxOP0z/U+58WDD01hAprNIV4eaXRwVYjLUkShsw==
    username: AgBks+iEzSv32SZSuacmXO1Xl6JG6vbru4vOBEC6OMoNooOoSQNV5z/gcoLTdw/r2YZ8g32FHVnKdOWUA7mXEeRXMxmsGodHxoKqMeJfh5/urmRbJ0bECBNSfU0UylBBPSN5MUWsKQJjgwXghNXw/V1bX9J3q1rmLTy0+aNG2xD4Prncc1zStvzMBNDPpDP0I0sJxF3xKgmC3+tsxDj6DMgsrZYYetrHUr6vlocY4kEPy75G7+AB/3mBmFdvi+XggpaiRf+NIbXeldt0mFHyzRjDTlI5OLk5kMc2XYnhGuxFe7EvFLke5m7J46c2YXDMkBK/T0634FqmI7rODP34UsOtioUdX7qijHuG+ue+AkDp1At58jTtdDxdW+LV+DAC+NSl+bRdi/AKSFUnGQYbicGLC77+jxiCFIMXI7Rs1/U0F72mv5D0wVkEQrMZjNMFojtiWyf8F2nnomEDbpIUgHpWGE3SwOTwXXN+l+nVDyo0FID1de55VNcZOyZL1oh0xGqUiXei8stUTcxTjcz3XThvy+w8BHo3vQx/rWWsJ/f4c223FngTv9854JIAOiddSrVtUa1ndfYsHZWOCGZ2VRogf2yL/r5dgEvlbEcBC5lj6NgjWqJbcK823fGEsBGeyxJgPUrfgjmqEZritPsN2Gw+JhKZFzRciGKxjKH/Gbdd9tulY9i7bVSzG8CjlBiVPdhU6JCX
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
