apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea-mariadb
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
        tier: mariadb
    spec:
      containers:
      - image: mariadb:10.6.0
        imagePullPolicy: IfNotPresent
        name: mariadb
        env:
        - name: TZ
          value: Europe/Berlin
        - name: MYSQL_DATABASE
          value: gitea
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mariadb.rootpassword}}" 
        - name: MYSQL_USER
          value: gitea
        - name: MYSQL_PASSWORD
          value: "{{ .Values.mariadb.password}}" 
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-mariadb-pvc
      restartPolicy: Always
