apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-postgres-pv
  resources:
    requests:
      storage: 1Gi
