apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-postgres-pv
  labels:
    type: local
spec:
  storageClassName: gitea-postgres-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/docker-volumes/gitea-db"
