---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: healthchecks
  namespace: healthchecks
spec:
  encryptedData:
    SUPERUSER_PASSWORD: AgCP8INg7jIp17BCNqnglePckUfNTqcVWKUKIK+Z6DDHSqBcCN1XaRwQMI2cIpgajMPEPdVgyqbIE30bFKezGtuTD1HNNXVFGDb2gCrr+BWqx+gAw35oBUfOqz+hKbEN1/+LBQT//tfqR2uVlcALdLzzSY5uuRq7VMUzQUXsGpuPVJnlsjs7CVi2uB5L9gHp0ag34mcnvqKbYQtZcycCJ8WLVUXHpwfj6SFLAW2rtvvMt2o+zKc5ig0oMxk9L+tJQ+uloAS35PCoYrngj9x1x9d6MdoVtPZtp0I6zOC6hpfijTN+g/QGWVP5/uq7gfzkv1RDAmdVdxd0UT7sABxxZVoNURczp6jP0YnDvwwFxDwBMEPwnI+LrOuCo9dSD1j1B5tTQjFQKdQJvz1162T6iIGwJhO4tLv8mjtYlsxd5fgPayWLRZEfkZMaIZEaDJZtYY8k83s8oczKjR2WLTIuKhtr99GUSwDS3TVR8HU0DABjmc8Ws3rp2DWGzdPByqSc0w2udVMIGPFSUftGcS3jRGtt7+rMS0WP4IbAp0ICOdbUY6R6WUUiCiYfpLcvEze+yfKoiclFifc1kZkWIAwBI/bL9fi+evAW+K3KtFF0sQx6f/kARjm/ymZTL/oR62+OTymf8nFCPfEx9xi6AvXCeUTGYwEU+Xl+hIq8Qi8YuFPCApk/dbg9SIQ6MuIbLwDG4qqlfrvQfaURBaG9usxon36z
  template:
    metadata:
      creationTimestamp: null
      name: healthchecks
      namespace: healthchecks
    type: Opaque
