apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: healthchecks
  name: healthchecks
  namespace: healthchecks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecks
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: healthchecks
    spec:
      containers:
      - image: linuxserver/healthchecks
        imagePullPolicy: Always
        name: healthchecks
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: SITE_ROOT
          value: https://healthchecks.nuc.local
        - name: SITE_NAME
          value: mysite
        - name: DEFAULT_FROM_EMAIL
          value: nevermind@itobey.dev
        - name: EMAIL_HOST
          value: 192.168.0.34
        - name: EMAIL_PORT
          value: '2525'
        - name: EMAIL_HOST_USER
          value: test
        - name: EMAIL_HOST_PASSWORD
          value: test
        - name: EMAIL_USE_TLS
          value: 'False'
        - name: SUPERUSER_EMAIL
          value: test@itobey.dev
        - name: SUPERUSER_PASSWORD
          value: test
        - name: REGENERATE_SETTINGS
          value: 'True'
      restartPolicy: Always
