---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgB5iRossn9811MEAv0aTimGSKW6z/iaoal9jhRLRFsWV3kwVZcZ3xTs2HsfxBuetRn7T4LyBdc7LWvsQNSxfq47eXMU44pdcqosArC8MK+rNIvsdyCn+cBj7ICOWEcsY5jD/Aicm7eELlSBDbHqmwJBrty3nvNvnT1eQaXmfCHErrZ6dedHzhbXnIB2XmV8vcoDoTDXlH+ALQQgTPk32nQQ6zMV4H4JJB1sDATByn/VSddoC89oyaJlo8V8B9bVMy6fK/XzhdBU2KN44n7T8w0W9lwg0/v+9v8iuGQ5XYwJFdOa9ybbUt6jdmSyQwZsJw4SBo0reznuAtwdTPSoQcGscQxqiqOAK7Gyx8dK2hbCzBpZLJXcNZJcByggjMOebMcj47GdZyhewlnf2r46SgbrPwqLy+sU9Oe2knQ0SoxQcMoJQAkSeOOCsOAy8jvNhh6iDnw0773jlIteX88zB9Rlcx6Nbbjd+2SoEfORpA8S5md8FWbww06KeRXgApw9nGS01C9CUL5TaefIYv2SvD88OhG3HvdmwIIPQKNixjKShsjYvoquJEV5gceVgp11YQo9IUAqgWQv/oLeUdHgzVxWFMqMfWExP6vCeP/ixNjSbbZ2GZ7oLBByglSMh6NCbOpPgDOv7jmJ40wsfDWX3zdp+1qwzJ2z3muKE/gaTTPBvZHnytFFVxaRJ0o9mK2xRrdPwFf1b120KyjodyFa97qCyCfP1lftaKSFyROoRBBYvA==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
    type: Opaque
