apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datadog-api-collector
  name: datadog-api-collector
  namespace: datadog-api-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-api-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datadog-api-collector
    spec:
      containers:
      - image: ghcr.io/itobey/datadog-api-collector:0.2.2
        imagePullPolicy: IfNotPresent
        name: datadog-api-collector
        envFrom:
        - secretRef:
            name: datadog-api-collector-secret
        env:
        - name: DD_SITE
          value: datadoghq.eu
      restartPolicy: Always
