kind: Secret
apiVersion: v1
metadata:
  name: datadog-api-collector-secret
  namespace: datadog-api-collector
data:
  apikey: "{{ .Values.datadog.apikey}}"
  appkey: "{{ .Values.datadog.appkey}}"
type: Opaque
