---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: fddb-exporter
spec:
  encryptedData:
    FDDB-EXPORTER_NOTIFICATION_TELEGRAM_CHATID: AgAI3Ul7H9C5/EriChaXwjt5UXsqNg/mM25DqKBOlToKAGrkrfyI3bNYaqjABy8HhqhuJPchDH2sdU0UXyUWGJeOaRbuMqmGpycD35bd7AcrS+xdJQQZWUJLLgDBEZQqSlZCCAZUGLWkQwrZN730xOB4E1lYjvD85HM78N0jd6U0xTIZ0mHSjbt577vFJOi9nvzCoZJPGMwo0UlPDCCGZoaMIYZsA0TMTDVU01J5aR306tlF15Y9W0SJPD7lId7dDV994aTUWMLYK5TT/eJAygIhlMe9ouwL2YJ+9AYUfuZn+pGKe5A/a3jaIELCR/VYqJQgXBdN/aAaV/68TxVL4f+hyD4+ammso4JHY668je0Ptwh77d7W1NS8IgUExAHFWotNm7kHBv5ffeVV9JF9EfDxcfTA0rEsxSfSVyK9+bFzPa/eHwK8FLMwdXg7BeM7lc0LGOgC9/guDiXoLIXOAQ2M77o8TY0sTE+5jTxFQ6y3a7wGSgt4PcPpPMZCi6NEKZlT6LMa82E6mnCmNTcOHQdo4FTxNA8/2+7Vv451oYqXKC83cDQI+fH1EuAaWCGgc5xEyCyeoPn3E0ndDdG2KjHM6uRDogTuYns7psf7UOHE5DJ7WSL+tU29Fdh1ZF6oEaTpOte9DqqwcjkDVVJOPyR+8j/3zt+sxZvRFvGWy2uDCLPNYWNoGxMl0JqoZccVBcSzEUwXZ9MuWu+O
    FDDB-EXPORTER_NOTIFICATION_TELEGRAM_TOKEN: AgAPPx47YCwDNJq16QMrIHXLfebwZBXxNrolvtNR9Nmyp86myU9bBje8q5wEwzyanu84lEgsWkCdU3c/V6VRQkb/adgLbNzrz+P6+yeFZbpAGWt7LZBgBWb3QL3e8tzqks5rNld9oFKD1YEI1JbDlQRAKR7s3qjFFIw9ntc4dbKuPYf919y51d9GLzWf2Hk0BVrXlKlwWMcRc9xytIcqzOnGJtHnWMQU5yMm8k8NLF83Bso16nYmRfCM6Lj0qXJq6AFH4Ooz8+aCoW1lEC82P5kqnH3jif8jMUGVlVFqhqVx+f3GmCzLOo5XxEpY6pLoGycG/euLECeJL8HcQJwBC/0hmnOTcKg9orJLugn5fJ1hxn0RhqxkYusGHlUKWXb0ytSaR3BJKA17wAODESJiERTbguF+ey3cWhmis98/QgqsaJu9lJjJ42vdQRQebJ75Ict39OPrpKJ0iqWuXfFYp9NLinpB1RrrnKM82pNEWFdAeVBybmQmMn/HnCxUTBKRZv7z2KsZ1WJq8JAG1FNQuxnxibwKEdD8ObbkQ0zjkhD6rrcuFT2JlC6ejiwcAB6LcvZgEr4i4sDQ3fKBaGjIGvAwuXVx+ap5yznfJp8ZToXD5781rZrhrkEW2PTduzfE6+h7pZbChejqJaiKwxq1EoJnFG9Sb3ZzqWGzK7hHYAilvOA0PEO9RtxhMMoa615OtXGKneXdkaMsh4alGZegTTvRHGigt3uI3naveOZvq7E5n29brfkSVAgzc1baoIxc
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: fddb-exporter
    type: Opaque
