---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: fddb-exporter
spec:
  encryptedData:
    FDDB-EXPORTER_NOTIFICATION_TELEGRAM_CHATID: AgAeYWgOdmwY6qNjhtxNbm/zz9BlFJKatszPGR0HgZx2CpMf/3x3PqYdo1BFLmJAlIIi1mbvca/P3vLAmulryrsyldAw5fsLz+E0EbPvhyzZ6POKWxonZ86Ft8JYMhSqY1ZvBsv/pNFBd0gBHSmXBeHQBWrKlCDrCYOgH8wZeFgbQ0N+yTkJQYDhTzidF43g3u4pSbp4fEzCYXj2JpCWY3Q8KqLpilXaomzjVcyz/tUzgjE6tm81gMbkKh2+YoNOta7Q4uWgMyHqMS/CG4DU7+v7vft80NSdP000EZfDZsj5bBZ5OOFLMWwP4FUV/ZKOUigpgDq39M6nVjFFjoUx+vsjl1NupyDXRMSHyQ+FgLK9d+2YEdYg3qluIs+9G+VTGLtyo3Vby/zp/R0Ghgd9ksJghql5DG3kyKBMaJz6cCHJCAugHXAwxulCsJfi+TrWkmwhvyROuhOLFCvqV/fjncP7vvu8pcZktV5/bIfe0m0Cc3nfZY+eOtIy41e6EXjvftlvKVxNBcr05z2H5pK+ZJ4iBbwiyvbs+rEIVo2jC9TOFO+Iggsgg0l6xS69R9NMdarAOUxV8RRN8s1BJ7FZRrQsDYYbWvMeBQa6nHOQuPkq1NnuFqn92AzXgK0X1tkKA0QR/WQqu8YHLJufmcm8o32yaxAU7W79vOIo6mipFS+P+pXu0ePYrAc0OFTFuLFBV+Vg0icGqmrzmcWY
    FDDB-EXPORTER_NOTIFICATION_TELEGRAM_TOKEN: AgAdihhmAc0kC1IbGMPyazpGONp0+GQCPc9JxgtC7uoxdYaAx+68qj6GES0KZjW31mgEqbJFt/z4MGmbG1+pn1jxDBrH+Sd06kW519V1QiDj3VAy1jEYtG7+KkCcCrEzHAKGSjLtyVMpr4vLyykvGRq5NoySjoI0c/J358iiofjUL+DrRrmvRtpRGAWsqeMsLQ3+vDEd+FxxgOGbKn0FCG807WvfeIyVbWFQ/zzMGmEeu0Jwzb8+1nxQ3P+TvKvhooNxGZxN8MY5s/wsCbVB+G7hEWhulkR3JJZXwry2ou3wF32HeFbttk1DDOuHl+H4boxa9jAvoAZ8eACe+W3iRACBFqXUDbeyPqC+W8yJ63+Dvg1UuHFgeXEzR3qzgYyjIvftqOLBTdeGH/WvwWicpvu1SlRP6/g17LZBrnU/J9ucJGS43j02Wb9oaAcPr/upG6Em8I9Czd8ctJWrEAy3y7/kgcRgycrEGGVcqFzNGECoGj+HNOpqaz00SCgvkfN4Yb7FtZg3PeW4Sksi6OGuf3DeMbCOoWFYiusdKs9ymAChtRXDTdFCz/RAuAsKidmhNo+KMOlZ53K4kjqYGTjPJHvNj4Rj2jii0NP7Tj54po7Oiwn/1elLRLuno4w4o+2kJ6BySpecKWyl32Nxd/DKeMxPBQjA+25CuURohuUgATtNa8kj2EMg/wyutyGlI463dk7fCwKYFNJck5oO2Y/FYSoLhe3eD2/L0TvHVc6jzZAC0JnFqja0klaaOJlAMyUGSwiM
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: fddb-exporter
    type: Opaque
