apiVersion: v1
data:
  application.yml: |
    micronaut:
      application:
        name: fddbexporter
    datasources:
      default:
        url: jdbc:postgresql://postgres.misc:5432/postgres
        driverClassName: org.postgresql.Driver
        username: postgres
        password: "{{ .Values.postgres.password }}"
    jpa.default.properties.hibernate.hbm2ddl.auto: update
    fddb-exporter:
      fddb:
        cookie: "{{ .Values.fddb.cookie }}"
        basicauth: "{{ .Values.fddb.basicauth }}"
    logger:
      levels:
        root: INFO
kind: ConfigMap
metadata:
  name: fddb-exporter-config
  namespace: fddb-exporter
