---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-secret
  namespace: fddb-exporter
spec:
  encryptedData:
    FDDB-EXPORTER_INFLUXDB_TOKEN: AgBh4d+6sgDr0b5k+G1KBwpcp0Xouo/pyvCkdTNm6syK49ah8HnHdonTKc30KnwZULVz4STW3RyNuoF5C0FsMieEyU3JcYxOQMtlVo6r7FGuRDi8FMFtX6717nRfdLTplw/Iq3EYZimCEzgMUDeYF7ukr3UFVXlvCCTQMUHyvBF1uLqQHo9XPgUu8eZLd/gmvxp2bd3zkjn0757kcROHWScVNXX1qVfILU7tTgTAxxfgKLcPJRNqBGQc4I/OgaarystDl9P0ZSQTKwFgMBz7WmtRRo1rlEOWGxFFh4a27XyW0GXQVgR9fMgDnv8qViJHuDr3pNXdHogcaTwSVn+aOQRON1Is0oz/yKYZxL+iPUO0OBNJcwVb8KHT02Hk4EnKXv5vHH2mMhzmrTINotii/vO5Z9wNa/znxVRJWG3Z7N5Uhic1gGrFaeYvyarWMjCxsuH72yHWigUFCkD+gSz7JuUtEX2bmqyN0qXXKhpvv0Rgou2M4PBzI9YUXAkc8IfiPXlfFsLBKzJ98AfJCE2z4hVeZScIn/QupV/FL9RmDNKcIHacI8BCthb4SOIXoPPK5VWBgV+s/nKmlTfSl2RBqcUwpL2YaNUDCHEHs7zELjleFPrkP1eeDFBf8ndVv2Fs8QYDDhbHhANHQHggfKrlzSd3vv7IwdyxYjq/Rmum2ARroIXgoOzZYQ9ZUrUP/VelINLa+jiAwE3AANPphzxoeB0QJyY22wOu6OtnR9czX3VlsSF8V/VTkfQNSjhoD5Bv1A83jrlKLTnlLiTamf1Y2yKtNqcUpTkxWNcn7WnWdf4Gi+viHgFrxbgr
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-secret
      namespace: fddb-exporter
    type: Opaque