apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fddb-exporter
  name: fddb-exporter
  namespace: fddb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fddb-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fddb-exporter
    spec:
      containers:
      - image: ghcr.io/itobey/fddb-exporter/fddb-exporter:0.2
        imagePullPolicy: Always
        name: fddb-exporter
        env:
        - name: MICRONAUT_CONFIG_FILES
          value: /fddb-exporter/application.yml
        volumeMounts:
        - name: config-volume
          mountPath: /fddb-exporter/application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: fddb-exporter-config
      restartPolicy: Always
