---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: fddb-exporter
spec:
  encryptedData:
    SPRING_MONGODB_PASSWORD: AgCx2poiIFwonqbHX2y8fI7MudMHswTvUClDyXYSTSbxVuO4AZDW/HT8dHVfO8e1Du0jPeOjxoOWd7KAD5r/UC6Awz+OiLaoMxo94ZiluxgNXQQik+xbQwUq8FCIGns28q9u6WUGG1BA3lr6iozqqjD9PpYlsu8Si2mNSC9NnKg12z0Cw1CYizvgtNQLzxFL538Q7UwjxaJA6l+vbvJMvMg/jldzdYdZvw1nYjVilH8zIymdUAak05unQVntMNwA4LbhceyFj7lHKP3MeuIho2mupqGlZZRgWkqGlV4aMdHGvH/ajd/yGPNZzJKYFL3V+B7+TON3ezzj4WEYSFSNS/KKLz5Pe7UlgkaGTDwo08M2ITAKAe4OBxJem4tiPsK0QkcXvRmZoX61rVeZutuW5rScAqB/jwr12ntYsNXJEOIf3k1nwayeXIz5Yf3aONOkTZDIswW43kdp4hsT0R0lNkYqsbhQ3q+C1U+MpGVo3yM3NcPOdN3o9NsC5+7elfo9/CajT67fxhSkk/SDcpIwVNfLss+Xko7WERbeK93cQkvm0zCPcYOizkOu1gYd8wJHul1CEAAclytILQMxITNDB6NpVYBpIQPQg8pwRtPIAR2w1MuqG1JMjT4W8q6SRN/ehOeP2h9koHBzqrKu1R+DcI7m+StTCOMPdeep0dCai52fFBRw4KlPgsCUicYSPL50ndNC/a6skMCFMMtC4XjXcTgV
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: fddb-exporter
    type: Opaque