apiVersion: v2
appVersion: 1.17.1
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.3.0
description: Bridges events and allows you to control your Zigbee devices via MQTT
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/zigbee2mqtt
icon: https://www.zigbee2mqtt.io/images/logo.png
keywords:
- zigbee
- mqtt
- home-assistant
kubeVersion: '>=1.16.0-0'
maintainers:
- email: helm@movishell.pl
  name: ishioni
- email: miguelangel.santiago@hotmail.com
  name: masantiago
name: zigbee2mqtt
sources:
- https://github.com/Koenkk/zigbee2mqtt
version: 7.4.0
