---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: playlist-mirror
spec:
  encryptedData:
    .dockerconfigjson: AgBnBIwNfUbqefXMTwYc9y7j0czZc85C8ZWIZE8CnmZa29LVO0XPvi13Lk4zsSn48cNs5e4EUiIl/8+7ssupqmOsd6y9K0/0aXfaHkw5279FH91QNr1XL6+Y4xB/XuOypIh9PDVNkyqsAhHUFjvvKj/81cp+qqwokVzbf54RSFaezpFljz657nT+IC307Ujo3bBtdrWPUi5Yi/S8VFg/mmpLnx/+QI7kHBa8QOtgfBMvF6mogI8jX+9tVubh68GhKZtrs4fa38fNrDSyTYtjdk45QR6IsqGPlsQkdeTPbC8IlMy0vh/Ql/ux8q9TXjIuVxUFavjoKYJJcPhgi2BX8+cAUZOVOiGaQEJF+nhiP2mLSdkYVmlTewd/oGf6ZsNi4OpfxTsqSoIcbUvxa94B1EzmQ/rl9ko9wbu481gpwUdJXDfvXlBDz2Tt4bp0fArFmVM/PuFIRyIfZMONEaqdAjEhBQUKulsoyGszvS+KrQcdHkv7KXhJes5E/RGdwfPStZPyRhXqbmnBniJfpUMQcgmSVf0vNoxISs5c3kMw+GXBgpJog+xTvp2WaDOEh5TqlliidmzW81o+m8R0FS721mqqeUGaAgzLRf0hQDk5kFJWbFWVtYRtyYw65wC72Ka2dUNVf0S5cxH4kfcuX3/ibLDprI4GGU3p8iguLtF5HKVfr9JCOOB50d8d69bKStXC5ekOeEBXHT2LTGvxGW4fPSh2DnTqhDZdKEZUsp6yT5YJD9t5qAOVK/mIay5FHKAS79weYclco3ezA0PU78fHWJ6faYyd8IaoBynRC+Z3ZTymLZgpa//ijxRPakqkOX/wdA/8sDDoCsP/ydTjVKcQJ43RQJf3VtZpMOUt5OBdhNxgjBMnybXi/tFd/CQZGoGc8xhGPyxdRChcfHu3i8rTGJNHwIJVFp1CpTE2eMnWfEW1MCtXlK7JzodQxIpF2Gv3MWAXxPv8yA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: playlist-mirror
    type: kubernetes.io/dockerconfigjson
