apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playlist-mirror-pvc
  namespace: playlist-mirror
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: playlist-mirror-pv
  resources:
    requests:
      storage: 1Gi
