---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: playlist-mirror
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgA123YU2XHn7eAnDHdkvl5ZctFS9G1H2zUjipKukUhQyj7EHMOHU2HBEjPKTRMNVsMKJqqE3u7kwPrRt//DQsY3yqhOwOYInypSp51Jg4ZLvTnW96s/TlPsn95Rdg+F2BQ058wMobro3cf4ywcU3+kG6YO4PyJZD29jrdtZHUZT6tEG+KTZ07jSqWH4pwW8P/s3iqxZRL/Kdnr7Jt0yxNg5SnK84R2iAa9i3euWrPp1AdXQ70z0MtD8OcYLwcTiVUNTDcXAPqtK8pSkRIp15nTylzFZN/IeE7dL9yLNXF05GIL4uAQv6prcztEpJMXKtL56LpWHrmFPveicZPP3GyQCFslzX8hm6E8nlWrfuOQKagP/GM08Y7uOEDl/VU6EEUrpENgcU5uA7oKZnXtU1oNGkUUl6lVxa56pxyq7RTCfEY8BmwdwgDREE1M/4cQHQjExFBjmDQpz1DLHwHEpZT4/w/AQEDC40TG4wt+uBoTSTbH5R51dhv1JvXbUBR/9TGxCICbs2VREtfLw5uTr3CvsNZ0Ax0JtNQ7oNv/dZG9Uu/baPES7ldDCa4M8F8VYfO09lCtIglxsUdjJrIoiut12Ys6SHAhq3yYkOHVYwAg0/J+O+P8qwut5iFNIm5IfuXgx9yQ3eQiqmaYQR6wa+4Ki0/boL32zeg6yyPC8qvsJ19q7gTPs+zRUxBU3l4R7T8AHsEXn7u35JOijp8RlLbsAu0pyhkWerXDIgKiAGmoVGqwxmBaDr7yhUipE+MwT
    TELEGRAM_CHAT_ID: AgCIRNOxyrO3f6bRFXIV1cJ4NdmWQi8NyjshOry4UE4AJzWr1Wof6Da5Ktlg0MQcAR27tJ/QHSm5Uvk7Xz2Ctwh3Wk8lAI5J6kvnzh0eB5nzDFOuZas/OR0Mz8qhgSSoHpeKFDhR4zAQP3YU7eGrQB5Atafb6h0XWHGeWZ2NRv/tJj2i5F21vZ7Jb/kVu6Ar0ou1Aojsun4F6vpLQGmyee7kZoHIsi+dmWB1WTQuymmRw+lrWpf2Sg4vyzoK/Dg8ViBs8w4k5bg4pbwaFAGWZ1QFgy3i5gp5119btY+Pl1Zny4nOAO+kEtJhGzmkVwF4QNL5m55Ix1FzurPErQfWlUXjtdXadvmYOHON/+rUANfb5QJPYt0nLWP4U4RZfqVUT5KEM2IifwwsXj5D20wDD50XIwXP9PqMqGRvoR5Vj+hHWPxXdL8FDp8yY1SwtA75maXe/J5nKqF0qpm9BglPKlUnPAVnls1cKW4wKUSdTcG4sQjXT8Fk/+00FnlZZCZAOLwYgjgquBGJLlEm/KXfxZJVzXrdZqt0LnrFXY56jWL/VL1l8u8hcYLF2MLESzYKqYF9cLR+pwsTTgab9YSo0KvXKgM9dtAQjHILt4YRbwR2fZLwklFXte/DSPqoDW/yZVF7NH5blhPFFST7Fl1rjVUd8a6qQSde+skw1iz3S4aVv6l84VvuNpKDs8D9vwysZ9I14UaEkGHTVW8v
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: playlist-mirror
    type: Opaque
