apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:2.0.9
        imagePullPolicy: IfNotPresent
        name: influxdb
        env:
        - name: INFLUXDB_DB
          value: FritzBox
        - name: INFLUXDB_USER
          value: telegraf
        - name: INFLUXDB_USER_PASSWORD
          value: "{{ .Values.influxdb.user.password }}"
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        - name: config-volume
          mountPath: /etc/influxdb/influxdb.conf
          subPath: influxdb.conf
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
      - name: config-volume
        configMap:
          name: influxdb-config
      restartPolicy: Always
