---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb
  namespace: influxdb
spec:
  encryptedData:
    INFLUXDB_USER_PASSWORD: AgCCZ7gxGhDLBl45VUMQ5WlxX17P09Q1jJszmWSaHpNhDKdCRaZSmfVcts+A8zozWemSsKxqDL5BtUTiKlE5MZncjkxAYJLi2X2sMYxRzxi2KTXDG+eC55hwZdZPtQN7A6QTmVcfo+PlP4f0cjDnlYk/thMSZ9VtT13sJlZ0uniPfidrbqZ4P6pxiRzZ/mb3cG8C+n8/GEYNwTw40OzWNI/5Aa4UJzY2FETt/91T+QcRQuG1/3L4JsA8KgG2aW/oBIBZNYAUSHNqykG9YsYEEVnVw4Yo+bsgIRLddsRQuQaeQcbJkiXJ8t/dC7854VgRmUrGHK7vCM2eqKmqjVQlOi07ppURkWhwsHytDsKmLwa0HLu4cNEzO3U4iKa+VQ9oAJoiMOkflZLRvtDauetc2gl8RSBuyrBttuhFCNxNn9VLuCyTc+T+uU2Pu8b4S+cQC+kuTkaVX5z77fDN1+0OWNhjed8kwZHUzHlVWGTnyUdlL7t2IozHLjKWvDEqB4pvCCP0eb+DxMoZQgCWIW9QYNikWcjx/ZlnclXM2VfD4unqOXRj2skT6xJZ0moNzYKfoXgFs7Oqud7l63Nsm2mOs0rS1shFxUbmtJpDNoBT0hLCeCAMuZSpt2Mh6j++jGRDpf2C8KPjAaxdG4yKadIpyfAdIJsScrDPudiQ4nIr46afWTMwHJo+g+XnVwvP/vN58BoNnGgt6BF43t9/SRXTi9s2
  template:
    metadata:
      creationTimestamp: null
      name: influxdb
      namespace: influxdb
    type: Opaque
