apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resilio
  namespace: resilio
spec:
  rules:
  - host: resilio.nuc.local
    http:
      paths:
      - backend:
          service:
            name: resilio
            port:
              number: 8888
        path: /
        pathType: ImplementationSpecific
