apiVersion: v1
kind: PersistentVolume
metadata:
  name: resilio-pv
  labels:
    type: local
spec:
  storageClassName: resilio-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/resilio-data"
