apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-pvc
  namespace: node-red
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: node-red-pv
  resources:
    requests:
      storage: 1Gi
