apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-pv
  labels:
    type: local
spec:
  storageClassName: node-red-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/enc/docker-volumes/node-red"
